define:
  user:
    name: admin
    password: admin123
  auth:
    securityKey: 121231313131313
  druid:
    username: admin
    password: admin123
  mysql:
    write:
      url: jdbc:mysql://192.168.101.41:3306/perception_base?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: perception_master
      password: perception_master
    read1:
      url: jdbc:mysql://192.168.101.41:3306/perception_base?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: perception_slaver
      password: perception_slaver
    share:
      url: jdbc:mysql://192.168.101.41:3306/share?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: share_master
      password: share_master
    equipment:
      url: jdbc:mysql://192.168.101.41:3306/perception_equipment?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: equipment_master
      password: equipment_master
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://${define.user.name}:${define.user.password}@localhost:18010/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #instance-id: ${spring.cloud.client.ip-address}:${random.value}
    metadata-map:
      user.name: ${define.user.name}
      user.password: ${define.user.password}
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    bus:
      trace:
        enabled: true
    config:   #  优先读取本地配置
      allow-override: true
      override-none: true
      override-system-properties: false    # 是否覆盖Java运行时参数
  data:
    mongodb:
      host: localhost
      port: 27017
      database: perception
      #username: admin
      #password: '{cipher}a1d30c1325f1b0cd2e4619bff2be57bc32ae0413c0ce1fee07153b60bfa3a782'
  redis:
    host: localhost
    port: 6379
    password: admin123
    database: 2
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 10000
        min-idle: 0
    timeout: 10000
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
  zipkin:
    base-url: http://192.168.0.154:9411
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  boot:
    admin:
      client:
        #url: http://192.168.101.65:10000   springboot 项目配置项
        username: ${define.user.name}
        password: ${define.user.password}
        instance:
          metadata:
            user.name: ${define.user.name}
            user.password: ${define.user.password}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.lego.**: debug
  file: /home/work/logs/${spring.application.name}/error_log
  maxHistory: 200



feign:
  compression:
    request:
      enabled: true # 请求压缩
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
    max-connections: 500
    max-connections-per-route: 100

#feign:
#  hystrix:
#    enabled: true
# ribbon 的超时时间（<）hystrix的超时时间
#MaxAutoRetries+MaxAutoRetriesNextServer+(MaxAutoRetries *MaxAutoRetriesNextServer) =重试次数
#重试期间，时间超过了hystrix的超时时间，便会立即执行熔断，fallback
# ribbonTimeout = (ribbonReadTimeout + ribbonConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1);
#当ribbon超时后且hystrix没有超时，便会采取重试机制。当OkToRetryOnAllOperations设置为false时，只会对get请求进行重试
ribbon:
  ConnectTimeout: 3000  #ribbon 负载均衡连接超时时间
  ReadTimeout: 20000  #ribbon 负载均衡读取超时时间
  #MaxAutoRetries: 1   #同配置首台服务器重试1次
  #MaxAutoRetriesNextServer: 1  #配置其他服务器重试1次
  #OkToRetryOnAllOperations: false #否所有操作都重试

hystrix:
  threadpool:
    default:
      coreSize: 500
      maximumSize: 10
      maxQueueSize: -1
  command:
    default:
      fallback:
        enabled: true
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE  # 隔离策略
          semaphore:
            maxConcurrentRequests: 500  # 最大并发数
          thread:
            timeoutInMilliseconds: 60000




fpfile:
  path: D:\业务文档\测量\file
  url:  http://localhost:50010/survey/api-file/file/fpfile/download


sso:
  name: sso-server
  url_prefix: http://t.weather.sojson.com/api/weather


hdfs:
  storePath: /home/work/file/
  savePath: equipment


