eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #instance-id: ${spring.cloud.client.ip-address}:${random.value}
    metadata-map:
      user.name: ${define.security.name}
      user.password: ${define.security.password}
      management.context-path: ${server.servlet.context-path}/actuator

    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

    ## 监控地址 拼接  context-path
    home-page-url-path: ${server.servlet.context-path}
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    health-check-url-path: ${server.servlet.context-path}/actuator/health



jwt:
  exclude:
    urlPatterns:
      #- .*api-docs.*
      #- .*swagger.*
      - .*.*